{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full-stack.fullname" . }}-secrets
  labels:
    {{- include "full-stack.labels" . | nindent 4 }}
stringData:
  NEO4J_PASSWORD: {{ .Values.secrets.data.neo4jPassword | quote }}
  NEO4J_AUTH: neo4j/{{ .Values.secrets.data.neo4jPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.data.grafanaAdminPassword | quote }}
  API_JWT_SECRET: {{ .Values.secrets.data.apiJwtSecret | quote }}
{{- end }}
