{{- $name := include "full-stack.fullname" . -}}
{{- $secretName := default (printf "%s-secrets" $name) .Values.secrets.existingSecret -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}-neo4j
  labels:
    {{- include "full-stack.labels" . | nindent 4 }}
spec:
  serviceName: {{ $name }}-neo4j
  replicas: 1
  selector:
    matchLabels:
      {{- include "full-stack.selectorLabels" . | nindent 6 }}
      component: neo4j
  template:
    metadata:
      labels:
        {{- include "full-stack.labels" . | nindent 8 }}
        component: neo4j
    spec:
      containers:
        - name: neo4j
          image: {{ .Values.neo4j.image }}
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: NEO4J_AUTH
            - name: NEO4J_dbms_memory_heap_initial__size
              value: {{ .Values.neo4j.heap.init | quote }}
            - name: NEO4J_dbms_memory_heap_max__size
              value: {{ .Values.neo4j.heap.max | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.neo4j.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ $name }}-neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-neo4j
  labels:
    {{- include "full-stack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "full-stack.selectorLabels" . | nindent 4 }}
    component: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: http
    - name: bolt
      port: 7687
      targetPort: bolt
