apiVersion: 1
datasources:
  - name: Customer Health Metrics
    type: prometheus
    access: proxy
    url: http://otel-collector:9464
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
